server:
  port: 8080
service:
  local: 
    url: http://localhost:8081
  personne:
    url: http://localhost:8082
  reservation:
    url: http://localhost:8083
  image:
    url: http://localhost:8089
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gestion_salles_tp_physique
    username: root
    password: rootpass
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate: 
        format-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    
security:
    jwt:
      secret-key: 1af01228a69e2340e0706abe0ea8337420dda626d6f1dea5682db22766aa5809
      expiration-time: 3600000